
[theme]
primaryColor = "#4361ee"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#1f2937"
font = "Inter"

[server]
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200
